export const keywords = [
  "knowledge",
  "knowledge base",
  "knowledgebase",
  "portfolio",
  "linkedin",
  "Hai Nguyen",
  "development",
  "developer",
  "sharing",
  "web",
  "mobile",
  "brainstorm",
  "problem solving",
  "problems solving",
  "solving problems",
  "cms",
  "content management system",
  "drupal",
  "drupal 8",
  "drupal 9",
  "drupal 10",
  "drupal developer",
  "drupal module developer",
  "drupal module development",
  "drupal custom module development",
  "drupal custom module",
  "drupal tricks",
  "drupal tips",
  "drupal caching",
  "PHP",
  "PHP 7",
  "PHP 8",
  "iOS",
  "full-stack",
  "full stack",
  "backend",
  "back-end",
  "frontend",
  "front-end",
  "react",
  "react.js",
  "next.js",
];
